twitter-to-kafka-service:
  twitter-keywords:
    - Java
    - MicroServices
    - Elasticsearch
    - Spring
    - Kafka
  enable-mock-tweets: true
  mock-min-tweet-length: 5
  mock-max-tweet-length: 15
  mock-sleep-ms: 10000
